FROM payara/server-full:6.2024.3-jdk17

COPY postgresql-42.7.2.jar /opt/payara/appserver/glassfish/domains/domain1/lib/
COPY jackson-datatype-jsr310-2.17.2.jar /opt/payara/appserver/glassfish/domains/domain1/lib/
COPY jackson-databind-2.17.2.jar /opt/payara/appserver/glassfish/domains/domain1/lib/
COPY jackson-core-2.17.2.jar /opt/payara/appserver/glassfish/domains/domain1/lib/
COPY jackson-annotations-2.17.2.jar /opt/payara/appserver/glassfish/domains/domain1/lib/