FROM payara/server-full:5.2022.5-jdk11

COPY postgresql-42.7.2.jar /opt/payara/appserver/glassfish/domains/domain1/lib/
COPY jackson-datatype-jsr310-2.17.2.jar /opt/payara/appserver/glassfish/domains/domain1/lib/
COPY jackson-databind-2.17.2.jar /opt/payara/appserver/glassfish/domains/domain1/lib/
COPY jackson-core-2.17.2.jar /opt/payara/appserver/glassfish/domains/domain1/lib/
COPY jackson-annotations-2.17.2.jar /opt/payara/appserver/glassfish/domains/domain1/lib/
COPY jjwt-api-0.11.5.jar /opt/payara/appserver/glassfish/domains/domain1/lib/
COPY jjwt-impl-0.11.5.jar /opt/payara/appserver/glassfish/domains/domain1/lib/
COPY jjwt-jackson-0.11.5.jar /opt/payara/appserver/glassfish/domains/domain1/lib/