server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 1) route на caller-service по serviceId
        - id: caller-service
          uri: lb://caller-service
          predicates:
            - Path=/caller/**

        # 2) прямой route на Payara
        - id: payara-direct
          uri: http://payara-1:8080
          predicates:
            - Path=/payara/**
          filters:
            # /payara/foo → /foo на payara-1
            - RewritePath=/payara/(?<segment>.*), /${segment}
