server:
  port: 8080

spring:
  application:
    name: api-gateway

  autoconfigure:
    exclude:
      - org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistrationAutoConfiguration

  cloud:
    discovery:
      enabled: true   # чтобы gateway использовал всех discovery-клиентов (Eureka + Consul)

    consul:
      host: called-consul   # имя сервиса consul из docker-compose
      port: 8500
      discovery:
        enabled: true
        register: false     # gateway сам в Consul не регистрируем, он только клиент

    gateway:
      discovery:
        locator:
          enabled: true     # чтобы можно было ходить по lb://serviceId
      routes:
        # 1) route на caller-service по serviceId (через Eureka)
        - id: caller-service
          uri: lb://caller-service
          predicates:
            - Path=/caller/**

        # 2) route на Payara через Consul + LoadBalancer
        - id: payara
          uri: lb://called-service     # ВАЖНО: имя сервиса в Consul
          predicates:
            - Path=/called/**
          filters:
            # /payara/foo → /foo на Payara
#            - RewritePath=/called/(?<segment>.*), /${segment}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

