server:
  port: 0

spring:
  application:
    name: called-adapter

  gateway:
    url: http://api-gateway:8080

  autoconfigure:
    exclude:
      - org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistrationAutoConfiguration

  cloud:
    consul:
      host: called-consul
      port: 8500
      discovery:
        register: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
